// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEBMPWF-S2_DmkrkOPDimliMTxUIJE9UE',
    appId: '1:651928555470:web:a3936810f754722e6b259f',
    messagingSenderId: '651928555470',
    projectId: 'simple-auth-1-26d7d',
    authDomain: 'simple-auth-1-26d7d.firebaseapp.com',
    storageBucket: 'simple-auth-1-26d7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSbJqZYDhrcr5XRkC8mE2l_dSlEQTUQY',
    appId: '1:651928555470:android:ee8a175cd33864156b259f',
    messagingSenderId: '651928555470',
    projectId: 'simple-auth-1-26d7d',
    storageBucket: 'simple-auth-1-26d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOngELipJJmr_ChMox1agMTuIqSCcA-yM',
    appId: '1:651928555470:ios:211b26ceb4cb3d126b259f',
    messagingSenderId: '651928555470',
    projectId: 'simple-auth-1-26d7d',
    storageBucket: 'simple-auth-1-26d7d.appspot.com',
    androidClientId: '651928555470-5cmd65159g7kq9a08pcjarenbp4in1uo.apps.googleusercontent.com',
    iosClientId: '651928555470-i9tdtvlrq2ae72pcu2j5tprikmark235.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOngELipJJmr_ChMox1agMTuIqSCcA-yM',
    appId: '1:651928555470:ios:211b26ceb4cb3d126b259f',
    messagingSenderId: '651928555470',
    projectId: 'simple-auth-1-26d7d',
    storageBucket: 'simple-auth-1-26d7d.appspot.com',
    androidClientId: '651928555470-5cmd65159g7kq9a08pcjarenbp4in1uo.apps.googleusercontent.com',
    iosClientId: '651928555470-i9tdtvlrq2ae72pcu2j5tprikmark235.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFirebase1',
  );
}
